
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Fri May 30 18:18:10 CST 2025
//----------------------------------------------------

package com.bocchi.MapGenerator.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TORRE_CASTILLO = 9;
  public static final int CUEVA = 8;
  public static final int PIEDRA_MARMOL = 7;
  public static final int PUNTOYCOMA = 20;
  public static final int ARBOL = 2;
  public static final int PIEDRA = 4;
  public static final int PAREN_ABRE = 21;
  public static final int PINO = 3;
  public static final int CASTILLO = 17;
  public static final int ANIMAL = 13;
  public static final int PERSONA = 14;
  public static final int NUM = 18;
  public static final int DRAGON = 15;
  public static final int COMA = 19;
  public static final int PAREN_CIERRA = 22;
  public static final int EOF = 0;
  public static final int PIEDRA_CALIZA = 5;
  public static final int PIEDRA_GRANITO = 6;
  public static final int error = 1;
  public static final int CASA_PIEDRA = 12;
  public static final int CASA = 10;
  public static final int CASA_MADERA = 11;
  public static final int MOUNSTRO = 16;
}

