
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sat May 31 00:22:55 CST 2025
//----------------------------------------------------

package com.bocchi.MapGenerator.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TORRE_CASTILLO = 16;
  public static final int CUEVA = 4;
  public static final int PIEDRA_MARMOL = 14;
  public static final int PUNTOYCOMA = 21;
  public static final int ARBOL = 3;
  public static final int PIEDRA = 7;
  public static final int PAREN_ABRE = 18;
  public static final int PINO = 2;
  public static final int CASTILLO = 9;
  public static final int ANIMAL = 5;
  public static final int PERSONA = 8;
  public static final int NUM = 17;
  public static final int DRAGON = 6;
  public static final int COMA = 20;
  public static final int PAREN_CIERRA = 19;
  public static final int EOF = 0;
  public static final int PIEDRA_CALIZA = 13;
  public static final int PIEDRA_GRANITO = 15;
  public static final int error = 1;
  public static final int CASA_PIEDRA = 12;
  public static final int CASA_MADERA = 11;
  public static final int MOUNSTRO = 10;
}

